export const ErrorCodes = {
  // Auth Errors
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  
  // Validation Errors
  VALIDATION_FAILED: "VALIDATION_FAILED",
  VALIDATION_SCHEMA: "VALIDATION_SCHEMA",
  VALIDATION_INVALID_CURSOR: "VALIDATION_INVALID_CURSOR",
  
  // Resource Errors
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_ARCHIVED: "RESOURCE_ARCHIVED",
  RESOURCE_DELETED: "RESOURCE_DELETED",
  
  // State Errors
  STATE_TRANSITION_INVALID: "STATE_TRANSITION_INVALID",
  STATE_ALREADY_IN_STATE: "STATE_ALREADY_IN_STATE",
  STATE_PRECONDITION_FAILED: "STATE_PRECONDITION_FAILED",
  
  // Team Errors
  TEAM_NOT_FOUND: "TEAM_NOT_FOUND",
  TEAM_LOCKED: "TEAM_LOCKED",
  TEAM_FULL: "TEAM_FULL",
  TEAM_ALREADY_EXISTS: "TEAM_ALREADY_EXISTS",
  TEAM_ALREADY_ARCHIVED: "TEAM_ALREADY_ARCHIVED",
  TEAM_INVALID_STATE: "TEAM_INVALID_STATE",
  TEAM_CAPTAIN_REQUIRED: "TEAM_CAPTAIN_REQUIRED",
  TEAM_MEMBER_ALREADY_EXISTS: "TEAM_MEMBER_ALREADY_EXISTS",
  TEAM_MEMBER_NOT_FOUND: "TEAM_MEMBER_NOT_FOUND",
  TEAM_JOIN_REQUEST_EXISTS: "TEAM_JOIN_REQUEST_EXISTS",
  TEAM_INVITATION_EXPIRED: "TEAM_INVITATION_EXPIRED",
  
  // Concurrency
  CONCURRENCY_CONFLICT: "CONCURRENCY_CONFLICT",
  
  // Rate Limiting
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED"
} as const;

export type ErrorCodeType = typeof ErrorCodes[keyof typeof ErrorCodes];
